before_install:
  git config user.name "Travis CI"

language:
  node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "0.12"
  - "iojs"
# dropped unsupport node versions on power arch
jobs: 
  exclude:
    - arch: ppc64le
      node_js: 0.12

after_script:
  npm run coveralls
